export default function StatsTable() {
  return (
    <div>
      <table>
        <colgroup span="16"></colgroup>
        <tr>
          <th>YR</th>
          <th>CLUB</th>
          <th>G</th>
          <th>AB</th>
          <th>R</th>
          <th>M</th>
          <th>2B</th>
          <th>3B</th>
          <th>HR</th>
          <th>RBI</th>
          <th>SB</th>
          <th>BB</th>
          <th>SLG</th>
          <th>OPS</th>
          <th>AVG</th>
          <th>WAR</th>
        </tr>
        <tr>
          <td>18</td>
          <td>Angels</td>
          <td>104</td>
          <td>326</td>
          <td>59</td>
          <td>93</td>
          <td>21</td>
          <td>2</td>
          <td>22</td>
          <td>61</td>
          <td>10</td>
          <td>37</td>
          <td>.564</td>
          <td>.925</td>
          <td>.285</td>
          <td>2.7</td>
        </tr>
        <tr>
          <td>19</td>
          <td>Angels</td>
          <td>106</td>
          <td>384</td>
          <td>51</td>
          <td>110</td>
          <td>20</td>
          <td>5</td>
          <td>18</td>
          <td>62</td>
          <td>12</td>
          <td>33</td>
          <td>.505</td>
          <td>.848</td>
          <td>.286</td>
          <td>2.5</td>
        </tr>
        <tr>
          <td>20</td>
          <td>Angels</td>
          <td>44</td>
          <td>153</td>
          <td>23</td>
          <td>29</td>
          <td>6</td>
          <td>0</td>
          <td>7</td>
          <td>24</td>
          <td>7</td>
          <td>22</td>
          <td>.366</td>
          <td>.657</td>
          <td>.190</td>
          <td>-0.1</td>
        </tr>
        <tr>
          <td>21</td>
          <td>Angels</td>
          <td>158</td>
          <td>537</td>
          <td>103</td>
          <td>138</td>
          <td>26</td>
          <td>8</td>
          <td>46</td>
          <td>100</td>
          <td>26</td>
          <td>96</td>
          <td>.592</td>
          <td>.965</td>
          <td>.257</td>
          <td>4.9</td>
        </tr>
        <tr>
          <td>MLB</td>
          <td>TOTALS</td>
          <td>412</td>
          <td>1400</td>
          <td>286</td>
          <td>370</td>
          <td>73</td>
          <td>15</td>
          <td>93</td>
          <td>247</td>
          <td>55</td>
          <td>188</td>
          <td>.537</td>
          <td>.890</td>
          <td>.284</td>
          <td>10.0</td>
        </tr>
      </table>
    </div>
  );
}
